package com.zalo.trainingmenu.downloader.base;

import android.content.Context;

import com.zalo.trainingmenu.R;

public interface Task extends Runnable{
    public static final String EXTRA_PROGRESS_SUPPORT = "progress_support";
    public static final String EXTRA_TASK_INFO = "task_info";

    public static final String RANGE_PROPERTY = "Range";
    public static final String CONTENT_LENGTH = "content-length";

    public static final String EXTRA_DOWNLOAD_ITEM = "download_item";
    public static final String EXTRA_TASK_ID = "notification_id";
    public static final String EXTRA_STATE = "state";
    public static final String EXTRA_PROGRESS ="progress";
    public static final String EXTRA_DOWNLOADED_IN_BYTES = "downloaded_in_bytes";
    public static final String EXTRA_FILE_CONTENT_LENGTH = "file_content_length";
    public static final String EXTRA_SPEED ="speed";
    String EXTRA_URL = "url";


    public static final int PENDING = 0;
    public static final int RUNNING = 1;
    public static final int PAUSED = 3;
    public static final int CONNECTING = 4;
    public static final int SUCCESS = 5;
    public static final int FAILURE_TERMINATED = 6;
    public static final int CANCELLED = 7;

    final static int TASK_CHANGED = 1;
    static final int TASK_RELEASE = 2;


    public static final int EXECUTE_MODE_NEW_DOWNLOAD = 5;

    public static final int EXECUTE_MODE_RESTART = 7;
    public static final int EXECUTE_MODE_RESUME = 8;

    long getLastExecutedTime();

    long getCreatedTime();

    long getFirstExecutedTime();

    long getFinishedTime();

    void setFinishedTime(long finishedTime);

    long getRunningTime();

    String getFileTitle();

    String getDirectory();

    String getURLString();

    float getProgress();

    int getProgressInteger();

    int getState();

    int getId();

    String getMessage();

    boolean isProgressSupport();

    long getDownloadedInBytes();

    long getFileContentLength();
    int getMode();

    void setMode(int mode);

    void resumeByUser();
    void restartByUser();

    float getSpeedInBytes();

    static String getStateName(int state) {
        switch (state) {
            case PENDING: return "Pending";
            case RUNNING: return "Running";
            case FAILURE_TERMINATED: return "Failure Terminated";
            case SUCCESS: return "Success";
            case PAUSED: return "Paused";
            case CANCELLED: return "Cancelled";
            case CONNECTING: return "Connecting";
            default: return null;
        }
    }

    static String getStateName(Context context, int state) {
        if(context==null) return getStateName(state);
        switch (state) {
            case PENDING: return context.getResources().getString(R.string.pending);
            case RUNNING: return context.getResources().getString(R.string.running);
            case FAILURE_TERMINATED: return context.getResources().getString(R.string.failed);
            case SUCCESS: return context.getResources().getString(R.string.success);
            case PAUSED: return context.getResources().getString(R.string.paused);
            case CANCELLED: return context.getResources().getString(R.string.cancelled);
            case CONNECTING: return context.getResources().getString(R.string.connecting);
            default: return "";
        }
    }

    boolean isAutogeneratedTitle();

    boolean isAutogeneratedPath();
}
