package com.zalo.trainingmenu.downloader.model;

import com.zalo.trainingmenu.util.Util;

import static com.zalo.trainingmenu.util.Util.generatePath;
import static com.zalo.trainingmenu.util.Util.generateTitle;

public final class DownloadItem {
    private final String mUrl;

    private final String mFileTitle;
    private final String mDirectoryPath;

    private final boolean mIsAutoGeneratedTitle;
    private final boolean mIsAutoGeneratedPath;

    public boolean isAutogeneratedTitle() {
        return mIsAutoGeneratedTitle;
    }

    public boolean isAutogeneratedPath() {
        return mIsAutoGeneratedPath;
    }

    public DownloadItem(String url, String title, String directoryPath) {
        this.mUrl = url;

        if(directoryPath!=null && !directoryPath.isEmpty()) {
            this.mDirectoryPath = directoryPath;
            this.mIsAutoGeneratedPath = false;
        } else {
            this.mIsAutoGeneratedPath = true;
            this.mDirectoryPath = generatePath();
        }

        if(title!=null && !title.isEmpty()) {
            this.mIsAutoGeneratedTitle = false;
            this.mFileTitle = title;
        } else {
            this.mIsAutoGeneratedTitle = true;
            this.mFileTitle = Util.generateTitle(mUrl,mDirectoryPath);
        }
    }

    public DownloadItem(String url) {
        this.mUrl = url;
        this.mIsAutoGeneratedTitle = true;
        this.mIsAutoGeneratedPath = true;

        this.mDirectoryPath = Util.generatePath();
        this.mFileTitle = Util.generateTitle(mUrl,mDirectoryPath);
    }

    public DownloadItem(String url, String title) {
        this.mUrl = url;

        this.mIsAutoGeneratedPath = true;
        this.mDirectoryPath = generatePath();

        if(title!=null && !title.isEmpty()) {
            this.mFileTitle = title;
            this.mIsAutoGeneratedTitle = false;
        } else {
            this.mFileTitle = generateTitle(url,mDirectoryPath);
            this.mIsAutoGeneratedTitle = true;
        }
    }

    public String getUrlString() {
        return mUrl;
    }

    public String getFileTitle() {
        return mFileTitle;
    }


    public DownloadItem(DownloadItem item) {
        this.mUrl = item.mUrl;
        this.mFileTitle = item.mFileTitle;
        this.mDirectoryPath = item.mDirectoryPath;
        this.mIsAutoGeneratedTitle = item.mIsAutoGeneratedTitle;
        this.mIsAutoGeneratedPath = item.mIsAutoGeneratedPath;
    }

    public String getDirectoryPath() {
        return mDirectoryPath;
    }

}
